### PR TITLE
fixed import roster

### PR DESCRIPTION
**Pull request by Searay-330**
#212 resolved

### CODE REVIEW

**Review by khoj-pez — APPROVED** [review]
Works fine!

**Comment by daviddob** [comment]
@dhruv0215 It may work...but its a convoluted mess if you need to check == true...better fix would be to make it a bool in the first place?

**Comment by Searay-330** [comment]
Java script does not contain anyway to convert a string to Boolean without doing a == comparison

**Comment by daviddob** [comment]
But why use a string in the first place for something that is supposed to be boolean?

**Comment by khoj-pez** [comment]
@daviddob I didn't write this function but I just looked at what the request should be in the docs and "complete" is indeed supposed to be a boolean. Front-end might've changed it so the request is sending a string instead of a boolean. I agree that is is better if it's left a boolean unless @Searay-330 had a strong reason to change it.

**Comment by Searay-330** [comment]
I didnt change it you can send a Boolean in form data it converts it to a string this as far as I can is standard procedure

**Pull request merged**
