### PR TITLE
Collab - CSV student import

### PR DESCRIPTION
**Pull request by Catuyn**
#135 
CSV import and button call to importRoster added.

### CODE REVIEW

**Review by rhanulewicz — CHANGES_REQUESTED** [review]
There is a syntax error on line 85 in AddUser.js. It won't compile. There also appear to be other syntax errors as well in the same file. Please test your work before sending a pull request.

**Comment by Catuyn** [comment]
updated

**Comment by rhanulewicz** [comment]
Still crashes. Please make sure it works on your end before sending it our way. 
image

**Comment by Catuyn** [comment]
I don't have ubuntu to follow your instructions and I don't know how to test it

**Comment by rhanulewicz** [comment]
Well that's definitely something that needs to be resolved *before* you starting working on it. I can help you set up the environment on Ryver

**Comment by Catuyn** [comment]
At this point I don't know how to go about fixing this parsing issue, I must not be sending the .csv correctly. Any changes I make to the code result in the same parsing error on line 1 column 1.

**Comment by rhanulewicz** [comment]
Okay we've found a few issues. 

Firstly, in the CSV file you sent me, the course_num was invalid (fa17 should have been f17). That will cause issues.

Secondly, I misled you a bit earlier. callApi is used for api calls that don't need to send files. You should actually be using callApiWithFiles. Look at \client\util\apiCaller.js to see how to use that function. It's *slightly* different. (You dont need to specify "post" as the request type")

With both of those things fixed, it SHOULD work.

**Comment by Catuyn** [comment]
made the changes you suggested but im still getting errors
image

**Comment by rhanulewicz** [comment]
Ah, I see the problem. The value for the file should be formData1.files[0], not just formData1. Give that a shot.

**Review by rhanulewicz — DISMISSED** [review]

**Review by rhanulewicz — APPROVED** [review]
Good work. I know it was a bit difficult, and React is a big learning curve. Glad you could pull through.

**Pull request merged**
