### PR TITLE
Google OAuth Login and Logout Setup

### PR DESCRIPTION
**Pull request by techmamba24**
Done. #26

### CODE REVIEW

**Review by adhishchugh — COMMENTED** [review]
What's the purpose of the current_user route? Doesn't login automatically return the current user and redirect?

**Comment by techmamba24** [comment]
It's a route that the front-end can hit upon loading of any page and if it returns user it will know the user is logged in and if it does not, then the user is not logged in.

**Comment by adhishchugh** [comment]
Sounds good.

**Review by adhishchugh — APPROVED** [review]
Ready to merge

**Pull request merged**
